package presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.bo.PacienteBo;
import negocio.clases.Paciente;
import utilities.SwingUtilities;

/**
 *
 * @author Enzo Quartino Zamora
 * <github.com/enzocr || email: enzoquartino@gmail.com>
 */
@SuppressWarnings("serial")
public class MantPaciente extends javax.swing.JFrame {

    private PacienteBo bo;
    private DefaultTableModel modelPaciente;

    /**
     * Creates new form MantProfesor
     */
    public MantPaciente() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.edadTextField.setEnabled(false);
        this.bo = new PacienteBo();
        this.modelPaciente = new DefaultTableModel();
        fillTable();
    }

    private void fillTable() {

        this.modelPaciente = new DefaultTableModel() {
            private static final long serialVersionUID = 1L;

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        getTableDoctor().getTableHeader().setReorderingAllowed(false);

        getModelPaciente().setColumnCount(0);

        getModelPaciente().addColumn("# Asegurado");
        getModelPaciente().addColumn("Nombre");
        getModelPaciente().addColumn("Dirección");
        getModelPaciente().addColumn("Edad");
        getModelPaciente().addColumn("Fecha Nacimiento");
        getModelPaciente().addColumn("Correo");
        getModelPaciente().addColumn("Teléfono");
        getModelPaciente().addColumn("Profesión");

        List<Paciente> list = getBo().getAll();

        if (list != null) {
            getModelPaciente().setNumRows(list.size());

            for (int i = 0; i < list.size(); i++) {
                Paciente p = list.get(i);
                getModelPaciente().setValueAt(p.getNumAsegurado(), i, 0);//i=fila 0=columna
                getModelPaciente().setValueAt(p.getNombre(), i, 1);
                getModelPaciente().setValueAt(p.getDireccion(), i, 2);
                getModelPaciente().setValueAt(p.getEdad(), i, 3);
                getModelPaciente().setValueAt(p.getFechaNacimiento(), i, 4);
                getModelPaciente().setValueAt(p.getEmail(), i, 5);
                getModelPaciente().setValueAt(p.getTelefono(), i, 6);
                getModelPaciente().setValueAt(p.getProfesion(), i, 7);
            }
        }

        getTableDoctor().setModel(getModelPaciente());

    }

    private void fillTable(List<Paciente> list) {
        this.modelPaciente = new DefaultTableModel() {
            private static final long serialVersionUID = 1L;

            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };
        getTableDoctor().getTableHeader().setReorderingAllowed(false);

        getModelPaciente().setColumnCount(0);
        getModelPaciente().addColumn("# Asegurado");
        getModelPaciente().addColumn("Nombre");
        getModelPaciente().addColumn("Dirección");
        getModelPaciente().addColumn("Edad");
        getModelPaciente().addColumn("Fecha Nacimiento");
        getModelPaciente().addColumn("Correo");
        getModelPaciente().addColumn("Teléfono");
        getModelPaciente().addColumn("Profesión");

        if (list != null) {
            getModelPaciente().setNumRows(list.size());

            for (int i = 0; i < list.size(); i++) {
                Paciente p = list.get(i);
                getModelPaciente().setValueAt(p.getNumAsegurado(), i, 0);//i=fila 0=columna
                getModelPaciente().setValueAt(p.getNombre(), i, 1);
                getModelPaciente().setValueAt(p.getDireccion(), i, 2);
                getModelPaciente().setValueAt(p.getEdad(), i, 3);
                getModelPaciente().setValueAt(p.getFechaNacimiento(), i, 4);
                getModelPaciente().setValueAt(p.getEmail(), i, 5);
                getModelPaciente().setValueAt(p.getTelefono(), i, 6);
                getModelPaciente().setValueAt(p.getProfesion(), i, 7);
            }
        }

        this.tablePaciente.setModel(getModelPaciente());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numAseguradoTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        getByIdButton = new javax.swing.JButton();
        getByNameButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePaciente = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        direccionTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        profesionTextField = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        edadTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volverButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Mantenimiento de pacientes");

        jLabel2.setText("# Asegurado:");

        numAseguradoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numAseguradoTextFieldMouseClicked(evt);
            }
        });
        numAseguradoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numAseguradoTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre: ");

        nombreTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTextFieldMouseClicked(evt);
            }
        });
        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo:");

        correoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoTextFieldMouseClicked(evt);
            }
        });

        jLabel5.setText("Profesión:");

        deleteButton.setForeground(new java.awt.Color(204, 51, 0));
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Modificar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cleanButton.setText("Limpiar");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        getByIdButton.setText("Consultar por # asegurado");
        getByIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByIdButtonActionPerformed(evt);
            }
        });

        getByNameButton.setText("Consultar por nombre");
        getByNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getByNameButtonActionPerformed(evt);
            }
        });

        tablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePaciente);

        jLabel7.setText("Dirección:");

        direccionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionTextFieldMouseClicked(evt);
            }
        });
        direccionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextFieldActionPerformed(evt);
            }
        });

        telefonoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoTextFieldMouseClicked(evt);
            }
        });

        jLabel8.setText("Teléfono:");

        profesionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profesionTextFieldMouseClicked(evt);
            }
        });
        profesionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionTextFieldActionPerformed(evt);
            }
        });

        insertButton.setText("Agregar");
        insertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonMouseClicked(evt);
            }
        });

        jLabel6.setText("Fecha de nacimiento:");

        jLabel9.setText("Edad:");

        volverButton.setForeground(new java.awt.Color(255, 0, 0));
        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(getByNameButton)
                                    .addComponent(insertButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                                        .addComponent(getByIdButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(updateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cleanButton)
                                        .addGap(107, 107, 107)
                                        .addComponent(deleteButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel2))
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(numAseguradoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(nombreTextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(16, 16, 16)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(profesionTextField)
                                            .addComponent(direccionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(edadTextField)
                                            .addComponent(telefonoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                    .addComponent(volverButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addComponent(jScrollPane2))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(volverButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(numAseguradoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profesionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(correoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cleanButton)
                    .addComponent(deleteButton)
                    .addComponent(updateButton)
                    .addComponent(insertButton))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getByIdButton)
                    .addComponent(getByNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numAseguradoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numAseguradoTextFieldActionPerformed

    }//GEN-LAST:event_numAseguradoTextFieldActionPerformed

    private boolean validateData() {

        if (!SwingUtilities.includesValidChar(1, this.numAseguradoTextField.getText())) {
            SwingUtilities.showJOptionPane("Digite cedula del doctor");
            this.numAseguradoTextField.setBorder(SwingUtilities.colorBorder(1));
            return false;
        }
        if (!SwingUtilities.includesValidChar(2, this.nombreTextField.getText())) {
            SwingUtilities.showJOptionPane("Digite nombre del doctor");
            this.nombreTextField.setBorder(SwingUtilities.colorBorder(1));
            return false;
        }
        if (this.correoTextField.getText().isEmpty()) {
            SwingUtilities.showJOptionPane("Digite correo del doctor");
            this.correoTextField.setBorder(SwingUtilities.colorBorder(1));
            return false;
        }
        if (!SwingUtilities.includesValidChar(2, this.profesionTextField.getText())) {
            SwingUtilities.showJOptionPane("Digite especialidad del doctor");
            this.profesionTextField.setBorder(SwingUtilities.colorBorder(1));
            return false;
        }

        if (!SwingUtilities.includesValidChar(1, this.telefonoTextField.getText())) {
            SwingUtilities.showJOptionPane("Digite telefono del doctor");
            this.telefonoTextField.setBorder(SwingUtilities.colorBorder(1));
            return false;
        }

        return true;
    }
    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        cleanTextFields();
    }//GEN-LAST:event_cleanButtonActionPerformed


    private void tablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePacienteMouseClicked

        if (evt.getClickCount() == 2) {

            try {
                int row = tablePaciente.getSelectedRow();

                numAseguradoTextField.setText(getTableDoctor().getValueAt(row, 0).toString());
                nombreTextField.setText(getTableDoctor().getValueAt(row, 1).toString());
                direccionTextField.setText((getTableDoctor().getValueAt(row, 2).toString()));
                edadTextField.setText(getTableDoctor().getValueAt(row, 3).toString());
                datePicker.setDate(SwingUtilities.stringToDate(getTableDoctor().getValueAt(row, 4).toString()));
                correoTextField.setText(getTableDoctor().getValueAt(row, 5).toString());
                telefonoTextField.setText((getTableDoctor().getValueAt(row, 6).toString()));
                profesionTextField.setText(getTableDoctor().getValueAt(row, 7).toString());
                this.numAseguradoTextField.setEnabled(false);
            } catch (ParseException ex) {
                Logger.getLogger(MantPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_tablePacienteMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        if (validateData()) {

            Paciente obj = new Paciente(
                    Integer.parseInt(this.numAseguradoTextField.getText()),
                    this.nombreTextField.getText(),
                    this.direccionTextField.getText(),
                    this.datePicker.getDate(),
                    this.correoTextField.getText(),
                    Integer.parseInt(this.telefonoTextField.getText()),
                    this.profesionTextField.getText()
            );

            int res = getBo().update(obj);

            SwingUtilities.updateSwitch(res);

        }
        cleanTextFields();

    }//GEN-LAST:event_updateButtonActionPerformed


    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (numAseguradoTextField.getText().isEmpty()) {
            SwingUtilities.showJOptionPane("Seleccionar paciente a eliminar");
        } else {
            try {
                int numAsegurado = Integer.parseInt(numAseguradoTextField.getText());
                Paciente obj = new Paciente();
                obj.setNumAsegurado(numAsegurado);
                int res = getBo().delete(obj);
                SwingUtilities.deleteSwitch(res);
                cleanTextFields();

            } catch (NumberFormatException nfe) {
                SwingUtilities.showJOptionPane("Ingresar # de asegurado a eliminar (SOLO NUMEROS)");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    private void getByIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByIdButtonActionPerformed

        if (SwingUtilities.includesValidChar(1, this.numAseguradoTextField.getText())) {
            int cedula = Integer.parseInt(this.numAseguradoTextField.getText());
            Paciente obj = getBo().getById(cedula);
            List<Paciente> list = new ArrayList<>();
            list.add(obj);
            if (list.get(0).getDireccion() == null) {
                SwingUtilities.showJOptionPane("No hay registros");
                cleanTextFields();
            } else {
                fillTable(list);
            }
        }

    }//GEN-LAST:event_getByIdButtonActionPerformed

    private void getByNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getByNameButtonActionPerformed
        if (SwingUtilities.includesValidChar(2, this.nombreTextField.getText())) {
            List<Paciente> list = getBo().getByName(this.nombreTextField.getText());
            if (list.isEmpty()) {
                SwingUtilities.showJOptionPane("No hay registros");
                cleanTextFields();
            } else {
                fillTable(list);
            }
        }


    }//GEN-LAST:event_getByNameButtonActionPerformed

    private void direccionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTextFieldActionPerformed

    private void numAseguradoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numAseguradoTextFieldMouseClicked
        this.numAseguradoTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_numAseguradoTextFieldMouseClicked

    private void nombreTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextFieldMouseClicked
        this.nombreTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_nombreTextFieldMouseClicked

    private void correoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoTextFieldMouseClicked
        this.correoTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_correoTextFieldMouseClicked

    private void direccionTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionTextFieldMouseClicked
        this.direccionTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_direccionTextFieldMouseClicked

    private void telefonoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoTextFieldMouseClicked
        this.telefonoTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_telefonoTextFieldMouseClicked

    private void profesionTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profesionTextFieldMouseClicked
        this.profesionTextField.setBorder(SwingUtilities.colorBorder(2));
    }//GEN-LAST:event_profesionTextFieldMouseClicked

    private void insertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseClicked

        if (validateData()) {

            int cedula = Integer.parseInt(this.numAseguradoTextField.getText());
            Paciente p = getBo().getById(cedula);
            List<Paciente> list = new ArrayList<>();
            list.add(p);
            if (list.get(0).getDireccion() != null) {
                SwingUtilities.showJOptionPane("Ya existe un paciente con este # de cédula");

            } else {

                p = new Paciente(
                        Integer.parseInt(this.numAseguradoTextField.getText()),
                        this.nombreTextField.getText(),
                        this.direccionTextField.getText(),
                        this.datePicker.getDate(),
                        this.correoTextField.getText(),
                        Integer.parseInt(this.telefonoTextField.getText()),
                        this.profesionTextField.getText());

                int res = getBo().insert(p);

                SwingUtilities.registerSwitch(res);
                cleanTextFields();
            }

        }
    }//GEN-LAST:event_insertButtonMouseClicked

    private void profesionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionTextFieldActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        MenuPrincipal mant = new MenuPrincipal();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void cleanTextFields() {

        this.numAseguradoTextField.setEnabled(true);

        this.numAseguradoTextField.setText("");
        this.nombreTextField.setText("");
        this.direccionTextField.setText("");
        this.datePicker.setDate(new Date());
        this.correoTextField.setText("");
        this.telefonoTextField.setText("");
        this.profesionTextField.setText("");

        fillTable();
    }

    public JTable getTableDoctor() {
        return tablePaciente;
    }

    public void setTableDoctor(JTable tableDoctor) {
        this.tablePaciente = tableDoctor;
    }

    public DefaultTableModel getModelPaciente() {
        return modelPaciente;
    }

    public void setModelPaciente(DefaultTableModel modelPaciente) {
        this.modelPaciente = modelPaciente;
    }

    public PacienteBo getBo() {
        return bo;
    }

    public void setBo(PacienteBo bo) {
        this.bo = bo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MantPaciente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cleanButton;
    private javax.swing.JTextField correoTextField;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JTextField edadTextField;
    private javax.swing.JButton getByIdButton;
    private javax.swing.JButton getByNameButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField numAseguradoTextField;
    private javax.swing.JTextField profesionTextField;
    private javax.swing.JTable tablePaciente;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables

}
