/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Enzo Quartino Zamora
 * <github.com/enzocr || email: enzoquartino@gmail.com>
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctoresButton = new javax.swing.JButton();
        pacientesButton = new javax.swing.JButton();
        herramientasButton = new javax.swing.JButton();
        salonesButton = new javax.swing.JButton();
        examenesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        doctoresButton.setText("Mantenimiento de Doctores");
        doctoresButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctoresButtonMouseClicked(evt);
            }
        });

        pacientesButton.setText("Mantenimiento de Pacientes");
        pacientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesButtonActionPerformed(evt);
            }
        });

        herramientasButton.setText("Mantenimiento de Herramientas");
        herramientasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramientasButtonActionPerformed(evt);
            }
        });

        salonesButton.setText("Mantenimiento de Salones");
        salonesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salonesButtonActionPerformed(evt);
            }
        });

        examenesButton.setText("Mantenimiento de Examenes");
        examenesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examenesButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Menú Principal");

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(herramientasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pacientesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctoresButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salonesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(examenesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(150, 150, 150))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctoresButton)
                .addGap(18, 18, 18)
                .addComponent(pacientesButton)
                .addGap(18, 18, 18)
                .addComponent(herramientasButton)
                .addGap(18, 18, 18)
                .addComponent(salonesButton)
                .addGap(18, 18, 18)
                .addComponent(examenesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salirButton)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void herramientasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramientasButtonActionPerformed
        MantHerramientaMedica mant = new MantHerramientaMedica();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_herramientasButtonActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        LogIn mant = new LogIn();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    private void doctoresButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctoresButtonMouseClicked
        MantDoctor mant = new MantDoctor();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctoresButtonMouseClicked

    private void pacientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesButtonActionPerformed
        MantPaciente mant = new MantPaciente();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pacientesButtonActionPerformed

    private void salonesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salonesButtonActionPerformed
        MantSalon mant = new MantSalon();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salonesButtonActionPerformed

    private void examenesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examenesButtonActionPerformed
        MantExamenFisico mant = new MantExamenFisico();
        mant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_examenesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doctoresButton;
    private javax.swing.JButton examenesButton;
    private javax.swing.JButton herramientasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pacientesButton;
    private javax.swing.JButton salirButton;
    private javax.swing.JButton salonesButton;
    // End of variables declaration//GEN-END:variables
}
